name: Test Netdisco
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default:  false
#  push:
#    branches:
#      - master
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: 'netdisco/netdisco:latest-do'
      options: '--user root --entrypoint /bin/ash'
    steps:
#    - name: Check out latest code
#      env:
#        GITHUB_WORKSPACE: '/home/netdisco/git'
#      uses: actions/checkout@master
    - name: Get the Tag
      id: get_tag
      run: echo ::set-output name=TAGVALUE::${GITHUB_REF#refs/tags/}
#    - uses: shogo82148/actions-setup-perl@v1.12.2
#      with:
#        perl-version: 'latest'
    # Enable tmate debugging of manually-triggered workflows if the input option was provided
    - run: echo $PATH
    - run: id
    - run: pwd
    - run: echo 'if [ "$1" == "update" ]; then exec apk update; else exec apk add openssh xz tmux; fi' > /usr/local/bin/apt-get && chmod +x /usr/local/bin/apt-get
    - name: Setup tmate session
#      uses: mxschmitt/action-tmate@v3
      uses: lhotari/action-upterm@v1
      with:
        sudo: false
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}.
#    - run: 'cpanm --installdeps .'
#    - run: 'prove -vl xt/*.t'
