name: Test Netdisco
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Get the Tag
      id: get_tag
      run: echo ::set-output name=TAGVALUE::${GITHUB_REF#refs/tags/}
    - uses: shogo82148/actions-setup-perl@master
      with:
        perl-version: 'latest'
    - run: 'cpanm --installdeps .'
    - run: 'prove -v xt/*.t'
